### ISSUE TITLE
abnormal library behavior on threads 

### ISSUE THREAD

**Issue by mohsenomidi** [Fdhvdu/ThreadPool#4]
@Fdhvdu 
i just installed and execute your sample for thread pooling. after execution stage 1 (same result on other usage in all 3 remaining stages) i see the result below that it is not correct :

> stage 1
> add_and_detach - thread **4** wait 0 sec
> add_and_detach - thread **4** wait 0 sec
> add_and_detach - thread **4** wait 1 sec
> add_and_detach - thread **4** wait 3 sec

as you see the all thread shows **_number 4_**, as their thread no,  that it is not correct! you send the i as a variable to the function add_and_detach_func but it seems it is not working correctly

```
        for(size_t i{0};i!=tp.size();++i)
                tp.add_and_detach(add_and_detach_func,i);
```

```
        std::size_t add_and_detach_func(const std::size_t i)
        {
                using namespace std;
                const auto sec{get()};
                this_thread::sleep_for(chrono::seconds{sec});
                lock_guard<mutex> lock{mut};
                cout<<"add_and_detach - thread "<<i<<" wait "<<sec<<" sec"<<endl;
                return i;
        }
```

more info : 

Compiler : g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
OS:  Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-54-generic x86_64)

**Comment by Fdhvdu** [comment]
Actually this is a correct behavior. The behavior is as same as I wrote in [Warnings](https://github.com/Fdhvdu/ThreadPool#warnings).
(But the example do a misleading demonstration.)
I push a commit [here](https://github.com/Fdhvdu/ThreadPool/commit/71bb547b639b89ad097e17a5862b8953821926f0) to make it correct.
